package com.your.time.app.services

import com.your.time.app.domain.model.ImageModel
import com.your.time.app.domain.services.ActionImagesService

class ActionImagesServiceImpl : ActionImagesService {

    override fun getImages(): List<ImageModel>  = imageModels

    private val imageModels: List<ImageModel> by lazy{
         listOf(
                 ImageModel("ic_annonimus", tags = arrayListOf("аннонимус", "хакер")),
                 ImageModel("ic_athletics", tags = arrayListOf("спорт", "бег", "атлетика")),
                 ImageModel("ic_baby_bottle", tags = arrayListOf("бутылочка", "ребенок")),
                 ImageModel("ic_basket", tags = arrayListOf("корзина", "покупки", "шопинг")),
                 ImageModel("ic_batman", tags = arrayListOf("бетмен", "фильмы", "фантастика", "спасать мир")),
                 ImageModel("ic_beach", tags = arrayListOf("пляж", "загарать")),
                 ImageModel("ic_bench_press", tags = arrayListOf("спорт", "тяжести", "жим лежа")),
                 ImageModel("ic_books", tags = arrayListOf("книги", "книжная полка")),
                 ImageModel("ic_camera", tags = arrayListOf("камера", "фото", "видео")),
                 ImageModel("ic_car", tags = arrayListOf("машина", "авто", "транспорт", "дорога")),
                 ImageModel("ic_carousel", tags = arrayListOf("карусель", "развлечения", "мультики")),
                 ImageModel("ic_chat", tags = arrayListOf("чат", "общение")),
                 ImageModel("ic_cleaning", tags = arrayListOf("уборка", "работа по дому")),
                 ImageModel("ic_code", tags = arrayListOf("программирование")),
                 ImageModel("ic_comb", tags = arrayListOf("уход за собой", "расческа")),
                 ImageModel("ic_communicate", tags = arrayListOf("общение", "друзья")),
                 ImageModel("ic_conferention", tags = arrayListOf("конференция", "совещание", "люди")),
                 ImageModel("ic_controller", tags = arrayListOf("игры", "развлечения")),
                 ImageModel("ic_cookie", tags = arrayListOf("печенье", "еда", "перекус")),
                 ImageModel("ic_cube", tags = arrayListOf("кубик", "развлечения", "игры", "дети")),
                 ImageModel("ic_cycle", tags = arrayListOf("велосипед", "дорога", "транспорт")),
                 ImageModel("ic_darth_vader", tags = arrayListOf("Дарт Вейдер", "фильмы", "фантастика")),
                 ImageModel("ic_donation", tags = arrayListOf("пожертвавание", "забота", "уход")),
                 ImageModel("ic_facebook", tags = arrayListOf("Facebook", "социальные сети", "интернет")),
                 ImageModel("ic_fight", tags = arrayListOf("драка", "борьба", "спорт")),
                 ImageModel("ic_film_tape", tags = arrayListOf("фильм", "пленка")),
                 ImageModel("ic_fish", tags = arrayListOf("рыбки", "домашние животные")),
                 ImageModel("ic_fishing", tags = arrayListOf("рыбалка", "рыба", "удочка")),
                 ImageModel("ic_flower", tags = arrayListOf("цветы", "растения", "огород")),
                 ImageModel("ic_food", tags = arrayListOf("еда", "прием пищи")),
                 ImageModel("ic_football", tags = arrayListOf("футбол", "спорт", "мяч")),
                 ImageModel("ic_full_basket", tags = arrayListOf("корзина", "покупки", "шопинг", "магазин")),
                 ImageModel("ic_grandmother", tags = arrayListOf("родители", "бубушка", "родственники", "уход")),
                 ImageModel("ic_grandfather", tags = arrayListOf("родители", "дедушка", "родственники", "уход")),
                 ImageModel("ic_hard_work", tags = arrayListOf("работа")),
                 ImageModel("ic_headphones", tags = arrayListOf("музыка")),
                 ImageModel("ic_home", tags = arrayListOf("домашние дела", "дом")),
                 ImageModel("ic_hygiene", tags = arrayListOf("ванна", "гигиента", "уход за собой")),
                 ImageModel("ic_icecream", tags = arrayListOf("мороженое")),
                 ImageModel("ic_idea", tags = arrayListOf("идея", "творчетство")),
                 ImageModel("ic_innovation", tags = arrayListOf("идея", "творчество")),
                 ImageModel("ic_instagram", tags = arrayListOf("instagram", "социальные сети", "интернет")),
                 ImageModel("ic_jake", tags = arrayListOf("Джейк", "мультфильм", "развлечения")),
                 ImageModel("ic_kid", tags = arrayListOf("ребенок", "дети")),
                 ImageModel("ic_meditation", tags = arrayListOf("медитация", "спокойствие", "йога")),
                 ImageModel("ic_money", tags = arrayListOf("деньги")),
                 ImageModel("ic_moon", tags = arrayListOf("луна", "ночь", "астрономия")),
                 ImageModel("ic_note", tags = arrayListOf("музыка", "нота")),
                 ImageModel("ic_notebook", tags = arrayListOf("тетрать", "домашняя работа", "заметки")),
                 ImageModel("ic_pan", tags = arrayListOf("кулинария", "готовить", "еда")),
                 ImageModel("ic_park", tags = arrayListOf("прогулка", "парк")),
                 ImageModel("ic_pen", tags = arrayListOf("записать", "отредактировать", "карандаш")),
                 ImageModel("ic_portfolio", tags = arrayListOf("работа", "портфель")),
                 ImageModel("ic_pull_ups", tags = arrayListOf("спорт", "подтянивания")),
                 ImageModel("ic_reddit", tags = arrayListOf("reddit", "социальные сети", "интернет")),
                 ImageModel("ic_report", tags = arrayListOf("отчет", "работа")),
                 ImageModel("ic_restaurant", tags = arrayListOf("еда", "прием пищи", "ресторан")),
                 ImageModel("ic_rick_sanchez", tags = arrayListOf("Рик", "мультфильм")),
                 ImageModel("ic_sagar", tags = arrayListOf("сахар", "кулинария", "готовить еду")),
                 ImageModel("ic_sea", tags = arrayListOf("море", "плавать", "отдых")),
                 ImageModel("ic_sex", tags = arrayListOf("любовь")),
                 ImageModel("ic_sheet", tags = arrayListOf("лист")),
                 ImageModel("ic_sheet_music", tags = arrayListOf("музыка", "нота")),
                 ImageModel("ic_starfall", tags = arrayListOf("звездопад", "ночное небо", "астрология")),
                 ImageModel("ic_stroller", tags = arrayListOf("коляска", "ребенок", "дети", "гулять с ребенком")),
                 ImageModel("ic_support", tags = arrayListOf("поддержка", "помощь", "помогать")),
                 ImageModel("ic_theater", tags = arrayListOf("театр", "искусство", "развлечения")),
                 ImageModel("ic_tv", tags = arrayListOf("телевидении", "телевизор")),
                 ImageModel("ic_twitter", tags = arrayListOf("twitter", "социальные сети", "интернет")),
                 ImageModel("ic_vk", tags = arrayListOf("Вконтакте", "vk", "социальные сети", "интернет"))
        )
    }
}